### PR TITLE
Clarify Tarragona train stations

### PR DESCRIPTION
**Pull request by vdegove-ct**
- Explain that Camp Tarragona is way out of the city in info:language
- Take out Camp Tarragona of child stations of Tarragona (city). Note: this will only make the "blue warning" with the distance show up on Captain Train, but a research on Tarragona (all stations) will include results from this station as Renfe RS answers with those results.
- Explain that Tarragona Estació is central station in info:language
- Explain that "Tarragona" refers to all the stations in info:language (as Tarragona is also the
real name of the central station)

@mgalibert or @paulRbr please review, wait before for the go of translators.

### CODE REVIEW

**Comment by paulRbr** [comment]
Why should we include the distance in "Camp Tarragona" language information field? This is not the r of the Stations database.
(You can see that any other stations such as Aix TGV, Avignon TGV does not have this kind of info here)

**Comment by vdegove-ct** [comment]
Some stations have this information, when the TGV station name is not directly related to the city, like "Meuse TGV", "Futuroscope", "Champagne-Ardennes TGV", but that's for pure search optimization. In this case, you're right, it is not needed, I'll correct that.

We have always avoided to make an "all station" information field for any meta-station. However, as they haven't renamed central station to "Tarragona centro" when they opened the high-speed station and that central station is still officially Tarragona-full-stop, I think in this case it is deserved, what do you think?

**Comment by paulRbr** [comment]
That's great! Thanks!

**Comment by mgalibert** [comment]
I'm not comfortable with this decision. Adding `All stations` is not justified in my opinion. We have never done it before in similar situations. I remember `Benevento` for example. So I would remove the information of the meta-station to be consistent.

If needed we can change the name of `Tarragona Estacio` and replace it with `Tarragona Estacio Central`. I'm not sure the info in Spanish is relevant. Even though Catalan and Castillan are different languages, it's gonna look redundant / proximy because of the language proximity. Like writing `Paris (París)`

So to be consistent with what we usually do, I would just go for 
- `Camp Tarragona` + info `x km for Centre` as we do for TGVs stations.
- `Tarragona`
- `Tarragona Estacio Central` + info in all language without Spanish.

**Comment by mgalibert** [comment]
Actually if the only child station of `Tarragona` is `Tarragona Estacio`, I would just make `Tarragona Estacio` non suggestable. That's the way we do usually.

**Pull request merged**
